site_name: 'Tock'
site_description: 'Build assistants & chatbots with ease.'
site_author: 'VSCT'
site_url: 'https://voyages-sncf-technologies.github.io/tock/en'
repo_name: 'tock'
repo_url: 'https://github.com/voyages-sncf-technologies/tock'
edit_uri: ''
nav:
    - Introduction: index.md
    - Getting Started: getting-started.md
    - Build NLP model: build-nlp-model.md
    - Evaluate the model: evaluate-the-model.md
    - Tock APIs: api.md
    - The Open Data Bot: the-open-data-bot.md
    - Code a bot: code-a-bot.md
    - Test the bot: test-the-bot.md
    - i18n: i18n.md
    - KDoc: kdoc.md
    - Contribute: contribute.md
theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
copyright: 'Copyright &copy; 2017/2019 VSCT'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/voyages-sncf-technologies/tock'
