site_name: 'Tock'
site_description: 'The Open Conversation Kit'
site_author: 'Tock'
site_url: 'https://theopenconversationkit.github.io/tock/fr'
repo_name: 'tock'
repo_url: 'https://github.com/theopenconversationkit/tock'
edit_uri: ''
nav:
  - 'Accueil': 'index.md'
  - 'Table des matiÃ¨res': 'toc.md'
  - 'DÃ©couvrir Tock': # Guides / DÃ©couvrir
      - 'CrÃ©er son premier bot': 'guide/studio.md'
      - 'Configurer Slack': 'guide/slack.md'
      - 'Configurer Messenger': 'guide/messenger.md'
      - 'Programmer des parcours': 'guide/api.md'
      - 'DÃ©ployer avec Docker': 'guide/plateforme.md'
  - 'Utiliser Tock':
      - 'Concepts': 'utilisateur/concepts.md'
      - 'Tock Studio': 'utilisateur/studio.md'
      - 'Bot multicanal': 'utilisateur/canaux.md'
      - 'Bot multilingue': 'utilisateur/i18n.md'
  - 'DÃ©velopper avec Tock':
      - 'Modes disponibles': 'dev/modes.md'
      - 'Tock Bot API': 'dev/bot-api.md'
      - 'Tock Bot intÃ©grÃ©': 'dev/bot-integre.md'
      - 'Connecteurs': 'dev/connecteurs.md'
      - 'i18n': 'dev/i18n.md'
      - 'Liste des APIs': 'dev/api.md'
      - 'Exemples de code': 'dev/exemples-code.md'
  - 'Administrer Tock':
      - 'Architecture': 'admin/architecture.md'
      - 'Installation': 'admin/installation.md'
      - 'SÃ©curitÃ©': 'admin/securite.md'
      - 'DisponibilitÃ©': 'admin/disponibilite.md'
      - 'Supervision': 'admin/supervision.md'
      - 'Cloud': 'admin/cloud.md'
  - 'A propos':
      - 'Pourquoi Tock': 'apropos/pourquoi.md'
      - 'Vitrine utilisateurs': 'apropos/vitrine.md'
      - 'Prix et rÃ©compenses': 'apropos/recompenses.md'
      - 'Ressources': 'apropos/ressources.md'
      - 'Nous contacter': 'apropos/contact.md'
      - 'CommunautÃ©': 'apropos/communaute.md'
      - 'Contribuer': 'apropos/contribuer.md'
      - 'Emploi': 'apropos/emploi.md'
  - 'ðŸ‡«ðŸ‡· ðŸ‡¬ðŸ‡§': 'https://theopenconversationkit.github.io/tock/en/'
  - 'Tock.ai ðŸ”—': 'https://doc.tock.ai'

theme:
  name: 'material'
  language: 'fr'
  logo: 'assets/images/logo-white.svg'
  favicon: 'img/favicon.png'
plugins:
  - search:
      lang: 'fr'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
copyright: 'Copyright &copy; 2017/2020 Tock'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/theopenconversationkit/tock'
  search:
    language: 'fr'